### ISSUE TITLE
Article Decoding Error

### ISSUE THREAD

**Issue by kylefoley76** [nikita-moor/latin-dictionary#4]
I'm not able to use this dictionary.  When I type in a word such as 'amor' I get the error message: 'article decoding error'.  I'm using a mac 10.14.3

I have added the files like so:

<img width="916" alt="Screen Shot 2021-08-01 at 5 03 55 AM" src="https://user-images.githubusercontent.com/16620676/127770204-7e396786-bcaf-4265-b7ae-b0ee9fb1ba16.png">

I am able to search wikipedia articles on GoldenDict, so Goldendict is working, just not the Ramshorn dictionary.  I have hit the 'rescan' button.  Here is a screenshot of what my app looks like:

<img width="832" alt="Screen Shot 2021-08-01 at 5 06 07 AM" src="https://user-images.githubusercontent.com/16620676/127770257-7eaac68b-7cc5-43e9-9ba6-c0c0904bf9f9.png">

I downloaded the dictionary from here:

https://latin-dict.github.io/dictionaries/Ramshorn1860.html

**Comment by nikita-moor** [comment]
It's likely your GoldenDict is outdated, have you tried [Early Access Builds](https://latin-dict.github.io/docs/howto.html)? Also, you could try [other formats](https://github.com/nikita-moor/latin-dictionary/releases/tag/2019-07-10), such as MDict or StarDict.
P.S. Recent binaries of [GoldenDict++OCR](https://autoptr.top/gdocr/GoldenDict-OCR-Deployment/) may solve your problem... probably... if you find how to download them...
P.P.S. [Download](http://files.autoptr.top/d/31968491-43314173-bda923), password: `81autoptrtop`

**Comment by kylefoley76** [comment]
I've now downloaded the most up to date version of goldendict.  I'm still getting the same error.  However, I have reason to believe that at least some of the app is working.  For example, when I input 'fer' I get a list of all the words in the dictionary which begin with 'fer'.  
<img width="951" alt="Screen Shot 2021-08-10 at 5 55 49 PM" src="https://user-images.githubusercontent.com/16620676/128953605-d922cf9a-9c67-494a-a450-91ec6629e78a.png">

Stardict is out, it hasn't been updated since maybe 2010.  I cannot download from the sites that you linked to because they require both username and password and you only gave me the password.

Can you at least enable me to register at goldendict.org/forum?  Currently registration at that site is closed to new users and i see no way to write the mods of that forum in order to register.

**Comment by kylefoley76** [comment]
never mind. i got it.  the aard link works, the goldendict link does not, at least on macos

**Comment by nikita-moor** [comment]
> I've now downloaded the most up to date version of goldendict. I'm still getting the same error.

I can't help you if you don't say the exact place (website or URL) you have downloaded binaries from.

> Stardict is out, it hasn't been updated since maybe 2010.

I meant to download _my dictionary_ in StarDict (or MDict) format, not a dictionary shell.

>  I cannot download from the sites that you linked to because they require both username and password and you only gave me the password.

These credentials change over time. Login and password are on the [web page](https://autoptr.top/gdocr/GoldenDict-OCR-Deployment/) I linked in the previous post — search for "Root and Access Key".

> Can you at least enable me to register at goldendict.org/forum?

No. I am not related to the GoldenDict developers team and cannot help you with their infrastructure, but you can try contacting them directly on GitHub: <https://github.com/goldendict/goldendict>.

> never mind. i got it.

Glad you have solved the problem.
